-- Seed data for Telth Care Manager Assessment (50 MCQs + 6 written prompts + settings)
-- Safe to re-run: clears existing rows in these tables first.

truncate table mcq_questions restart identity cascade;
truncate table written_questions restart identity cascade;

insert into mcq_questions (source_no, section, question_text, options, is_active) values (1, 'A', 'You identify a repeated operational problem.', '[{"id": "opt1", "text": "Document it and propose a practical solution", "is_correct": true}, {"id": "opt2", "text": "Complain to colleagues", "is_correct": false}, {"id": "opt3", "text": "Ignore it", "is_correct": false}, {"id": "opt4", "text": "Tell customers management is poor", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (2, 'A', 'You miss your monthly target by 40%.', '[{"id": "opt1", "text": "Review activity, identify causes and create a recovery plan", "is_correct": true}, {"id": "opt2", "text": "Blame the market", "is_correct": false}, {"id": "opt3", "text": "Hide the numbers", "is_correct": false}, {"id": "opt4", "text": "Stop trying", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (3, 'A', 'You make an error in a patient follow-up.', '[{"id": "opt1", "text": "Report it appropriately, correct it safely and prevent recurrence", "is_correct": true}, {"id": "opt2", "text": "Hide it", "is_correct": false}, {"id": "opt3", "text": "Blame someone else", "is_correct": false}, {"id": "opt4", "text": "Change the record", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (4, 'A', 'A colleague performs much better than you.', '[{"id": "opt1", "text": "Learn from their process and improve your own", "is_correct": true}, {"id": "opt2", "text": "Discredit them", "is_correct": false}, {"id": "opt3", "text": "Stop cooperating", "is_correct": false}, {"id": "opt4", "text": "Assume they cheated", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (5, 'A', 'A task is due tomorrow and nobody is monitoring you.', '[{"id": "opt1", "text": "Complete it properly on time", "is_correct": true}, {"id": "opt2", "text": "Wait for a reminder", "is_correct": false}, {"id": "opt3", "text": "Do only part", "is_correct": false}, {"id": "opt4", "text": "Ignore it", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (6, 'A', 'You were paid an incentive larger than you earned.', '[{"id": "opt1", "text": "Notify finance/manager and request verification", "is_correct": true}, {"id": "opt2", "text": "Keep it", "is_correct": false}, {"id": "opt3", "text": "Spend it quickly", "is_correct": false}, {"id": "opt4", "text": "Tell friends but not Telth", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (7, 'A', 'A new Care Manager is struggling.', '[{"id": "opt1", "text": "Coach them using specific actions and follow-up", "is_correct": true}, {"id": "opt2", "text": "Tell them they are unsuitable", "is_correct": false}, {"id": "opt3", "text": "Criticize publicly", "is_correct": false}, {"id": "opt4", "text": "Ignore them", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (8, 'A', 'Which best describes good professional goals?', '[{"id": "opt1", "text": "Specific goals with measurable actions and review", "is_correct": true}, {"id": "opt2", "text": "Goals are unnecessary", "is_correct": false}, {"id": "opt3", "text": "Management decides everything", "is_correct": false}, {"id": "opt4", "text": "Wait for luck", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (9, 'A', 'A company process appears inefficient.', '[{"id": "opt1", "text": "Follow safe/lawful procedure while raising evidence-based improvements", "is_correct": true}, {"id": "opt2", "text": "Refuse it", "is_correct": false}, {"id": "opt3", "text": "Tell everyone to ignore it", "is_correct": false}, {"id": "opt4", "text": "Complain publicly", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (10, 'A', 'A patient complains angrily about a delay you did not cause.', '[{"id": "opt1", "text": "Listen, establish facts and help resolve/escalate", "is_correct": true}, {"id": "opt2", "text": "Argue", "is_correct": false}, {"id": "opt3", "text": "Ignore", "is_correct": false}, {"id": "opt4", "text": "Send them elsewhere", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (11, 'B', 'Before recording a vital sign, first verify:', '[{"id": "opt1", "text": "Patient identity and correct procedure/device readiness", "is_correct": true}, {"id": "opt2", "text": "Sales target", "is_correct": false}, {"id": "opt3", "text": "Social media", "is_correct": false}, {"id": "opt4", "text": "Nothing", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (12, 'B', 'A BP device gives an unexpectedly extreme reading.', '[{"id": "opt1", "text": "Recheck per protocol and escalate urgent/abnormal findings", "is_correct": true}, {"id": "opt2", "text": "Diagnose yourself", "is_correct": false}, {"id": "opt3", "text": "Ignore it", "is_correct": false}, {"id": "opt4", "text": "Change the value", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (13, 'B', 'A patient asks you to change a physician''s medicine dose.', '[{"id": "opt1", "text": "Explain that medication changes require an appropriately licensed clinician and arrange escalation", "is_correct": true}, {"id": "opt2", "text": "Change it", "is_correct": false}, {"id": "opt3", "text": "Ask another patient", "is_correct": false}, {"id": "opt4", "text": "Guess", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (14, 'B', 'A patient develops severe chest pain and breathing difficulty.', '[{"id": "opt1", "text": "Follow emergency escalation protocol and seek urgent medical assistance", "is_correct": true}, {"id": "opt2", "text": "Finish sales discussion", "is_correct": false}, {"id": "opt3", "text": "Wait until tomorrow", "is_correct": false}, {"id": "opt4", "text": "Only WhatsApp", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (15, 'B', 'Why is accurate patient identification important?', '[{"id": "opt1", "text": "Prevent record/test/follow-up mix-ups", "is_correct": true}, {"id": "opt2", "text": "Only billing", "is_correct": false}, {"id": "opt3", "text": "Optional", "is_correct": false}, {"id": "opt4", "text": "Only doctors need it", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (16, 'B', 'When using POCT equipment, follow:', '[{"id": "opt1", "text": "Manufacturer instructions, Telth SOP and applicable protocol", "is_correct": true}, {"id": "opt2", "text": "Whatever is fastest", "is_correct": false}, {"id": "opt3", "text": "A guess", "is_correct": false}, {"id": "opt4", "text": "Social media", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (17, 'B', 'A device is damaged or repeatedly errors.', '[{"id": "opt1", "text": "Remove/flag per procedure and escalate for technical review", "is_correct": true}, {"id": "opt2", "text": "Keep using it", "is_correct": false}, {"id": "opt3", "text": "Hide it", "is_correct": false}, {"id": "opt4", "text": "Change results", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (18, 'B', 'Patient information should be shared with:', '[{"id": "opt1", "text": "Authorized persons/systems for legitimate purposes with required consent/legal basis", "is_correct": true}, {"id": "opt2", "text": "Anyone asking", "is_correct": false}, {"id": "opt3", "text": "Friends", "is_correct": false}, {"id": "opt4", "text": "Social media", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (19, 'B', 'A Care Manager''s clinical role is to:', '[{"id": "opt1", "text": "Work within training/scope and coordinate with licensed clinicians", "is_correct": true}, {"id": "opt2", "text": "Diagnose/prescribe independently", "is_correct": false}, {"id": "opt3", "text": "Do any requested procedure", "is_correct": false}, {"id": "opt4", "text": "Replace specialists", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (20, 'B', 'After collecting a measurement:', '[{"id": "opt1", "text": "Record accurately and promptly in the correct record", "is_correct": true}, {"id": "opt2", "text": "Remember later", "is_correct": false}, {"id": "opt3", "text": "Round it to normal", "is_correct": false}, {"id": "opt4", "text": "Delete abnormal values", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (21, 'C', 'An RPM patient stops transmitting readings.', '[{"id": "opt1", "text": "Follow defined outreach/escalation workflow and document", "is_correct": true}, {"id": "opt2", "text": "Ignore", "is_correct": false}, {"id": "opt3", "text": "Invent readings", "is_correct": false}, {"id": "opt4", "text": "Cancel", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (22, 'C', 'Main purpose of a Connected Care Manager:', '[{"id": "opt1", "text": "Coordinate engagement, data, follow-up and escalation", "is_correct": true}, {"id": "opt2", "text": "Replace physician", "is_correct": false}, {"id": "opt3", "text": "Only sell", "is_correct": false}, {"id": "opt4", "text": "Only collect cash", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (23, 'C', 'A patient misses a diagnostic appointment.', '[{"id": "opt1", "text": "Follow up, understand barrier and help reschedule/escalate", "is_correct": true}, {"id": "opt2", "text": "Remove them", "is_correct": false}, {"id": "opt3", "text": "Scold", "is_correct": false}, {"id": "opt4", "text": "Ignore", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (24, 'C', 'A physician asks for home-monitoring trends.', '[{"id": "opt1", "text": "Provide accurate authorized data from approved system", "is_correct": true}, {"id": "opt2", "text": "Use memory", "is_correct": false}, {"id": "opt3", "text": "Send another patient''s data", "is_correct": false}, {"id": "opt4", "text": "Edit values", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (25, 'C', 'For an elderly patient living alone:', '[{"id": "opt1", "text": "Use defined follow-up, adherence support within scope, escalation contacts and safety awareness", "is_correct": true}, {"id": "opt2", "text": "Sell more products", "is_correct": false}, {"id": "opt3", "text": "No documentation", "is_correct": false}, {"id": "opt4", "text": "Never involve authorized caregivers", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (26, 'C', 'When handing over a patient:', '[{"id": "opt1", "text": "Use approved handover with relevant authorized information and pending actions", "is_correct": true}, {"id": "opt2", "text": "Give only name", "is_correct": false}, {"id": "opt3", "text": "Do nothing", "is_correct": false}, {"id": "opt4", "text": "Share publicly", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (27, 'C', 'A patient refuses a recommended service.', '[{"id": "opt1", "text": "Respect decision, explain appropriately, document and escalate if clinically necessary", "is_correct": true}, {"id": "opt2", "text": "Force it", "is_correct": false}, {"id": "opt3", "text": "Threaten", "is_correct": false}, {"id": "opt4", "text": "Charge anyway", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (28, 'C', 'Family requests confidential information but authorization is unclear.', '[{"id": "opt1", "text": "Verify authorization/consent and follow privacy procedure", "is_correct": true}, {"id": "opt2", "text": "Share all", "is_correct": false}, {"id": "opt3", "text": "Post in group", "is_correct": false}, {"id": "opt4", "text": "Guess", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (29, 'C', 'Best follow-up method:', '[{"id": "opt1", "text": "Consistent documented follow-up based on care plan/risk", "is_correct": true}, {"id": "opt2", "text": "Only when selling", "is_correct": false}, {"id": "opt3", "text": "Random", "is_correct": false}, {"id": "opt4", "text": "None", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (30, 'C', 'Repeated readings suggest deterioration.', '[{"id": "opt1", "text": "Follow defined clinical escalation pathway promptly", "is_correct": true}, {"id": "opt2", "text": "Diagnose", "is_correct": false}, {"id": "opt3", "text": "Wait weeks", "is_correct": false}, {"id": "opt4", "text": "Delete readings", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (31, 'D', 'A prospect says the Care Plan is too expensive.', '[{"id": "opt1", "text": "Understand need, explain relevant value/terms accurately and allow informed choice", "is_correct": true}, {"id": "opt2", "text": "Pressure them", "is_correct": false}, {"id": "opt3", "text": "Promise unlisted benefits", "is_correct": false}, {"id": "opt4", "text": "Insult competitors", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (32, 'D', 'Ethical healthcare selling means:', '[{"id": "opt1", "text": "Match appropriate services to genuine needs with accurate information", "is_correct": true}, {"id": "opt2", "text": "Sell everything", "is_correct": false}, {"id": "opt3", "text": "Hide charges", "is_correct": false}, {"id": "opt4", "text": "Create fear", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (33, 'D', 'Customer asks if a Care Plan guarantees recovery.', '[{"id": "opt1", "text": "Explain benefits accurately without guaranteeing clinical outcomes", "is_correct": true}, {"id": "opt2", "text": "Say yes", "is_correct": false}, {"id": "opt3", "text": "Invent statistics", "is_correct": false}, {"id": "opt4", "text": "Avoid", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (34, 'D', 'Best way to build a territory:', '[{"id": "opt1", "text": "Systematic partner/community mapping, outreach, follow-up and service quality", "is_correct": true}, {"id": "opt2", "text": "Wait for walk-ins", "is_correct": false}, {"id": "opt3", "text": "Spam", "is_correct": false}, {"id": "opt4", "text": "Copy lists unlawfully", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (35, 'D', 'A pharmacy sends ten interested customers.', '[{"id": "opt1", "text": "Use consent-based qualification, needs assessment and follow-up", "is_correct": true}, {"id": "opt2", "text": "Add to unrelated lists", "is_correct": false}, {"id": "opt3", "text": "Ignore", "is_correct": false}, {"id": "opt4", "text": "Promise free treatment", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (36, 'D', 'Best way to achieve monthly target:', '[{"id": "opt1", "text": "Track activities/conversion daily and adjust", "is_correct": true}, {"id": "opt2", "text": "Check last day only", "is_correct": false}, {"id": "opt3", "text": "Manipulate reports", "is_correct": false}, {"id": "opt4", "text": "Pressure unsuitable patients", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (37, 'D', 'Customer says a competitor is cheaper.', '[{"id": "opt1", "text": "Clarify needs and explain Telth differences/value accurately", "is_correct": true}, {"id": "opt2", "text": "Attack competitor", "is_correct": false}, {"id": "opt3", "text": "Lie", "is_correct": false}, {"id": "opt4", "text": "End conversation", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (38, 'D', 'When recommending marketplace/wellness products:', '[{"id": "opt1", "text": "Prioritize suitability, accurate claims and transparent terms", "is_correct": true}, {"id": "opt2", "text": "Make cure claims", "is_correct": false}, {"id": "opt3", "text": "Hide incentives", "is_correct": false}, {"id": "opt4", "text": "Push unnecessary products", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (39, 'D', 'A lead is not ready today.', '[{"id": "opt1", "text": "Set appropriate next step and follow up respectfully", "is_correct": true}, {"id": "opt2", "text": "Call continuously", "is_correct": false}, {"id": "opt3", "text": "Delete immediately", "is_correct": false}, {"id": "opt4", "text": "Threaten expiry", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (40, 'D', 'Sustainable Care Manager performance is:', '[{"id": "opt1", "text": "Quality service + retention + compliant growth + reliable collections", "is_correct": true}, {"id": "opt2", "text": "One day''s sales", "is_correct": false}, {"id": "opt3", "text": "Promises made", "is_correct": false}, {"id": "opt4", "text": "Complaints", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (41, 'E', 'A connected device fails to sync.', '[{"id": "opt1", "text": "Follow troubleshooting SOP, preserve accurate data and escalate unresolved issues", "is_correct": true}, {"id": "opt2", "text": "Invent data", "is_correct": false}, {"id": "opt3", "text": "Discard device", "is_correct": false}, {"id": "opt4", "text": "Blame patient", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (42, 'E', 'Unique patient records matter because of:', '[{"id": "opt1", "text": "Continuity, accuracy and prevention of record mixing", "is_correct": true}, {"id": "opt2", "text": "Only marketing", "is_correct": false}, {"id": "opt3", "text": "No reason", "is_correct": false}, {"id": "opt4", "text": "Public sharing", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (43, 'E', 'You accidentally open the wrong patient''s record.', '[{"id": "opt1", "text": "Stop, correct context and follow privacy/incident procedure if required", "is_correct": true}, {"id": "opt2", "text": "Continue", "is_correct": false}, {"id": "opt3", "text": "Copy it", "is_correct": false}, {"id": "opt4", "text": "Delete account", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (44, 'E', 'Patient asks for report through an unapproved channel.', '[{"id": "opt1", "text": "Use approved secure communication/consent process", "is_correct": true}, {"id": "opt2", "text": "Always comply", "is_correct": false}, {"id": "opt3", "text": "Group chat", "is_correct": false}, {"id": "opt4", "text": "Screenshot publicly", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (45, 'E', 'Your login password should be:', '[{"id": "opt1", "text": "Confidential and protected according to policy", "is_correct": true}, {"id": "opt2", "text": "Shared with team", "is_correct": false}, {"id": "opt3", "text": "Written publicly", "is_correct": false}, {"id": "opt4", "text": "Same for everyone", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (46, 'F', 'You receive a new territory with few contacts.', '[{"id": "opt1", "text": "Map partners and create measurable outreach plan", "is_correct": true}, {"id": "opt2", "text": "Wait", "is_correct": false}, {"id": "opt3", "text": "Complain", "is_correct": false}, {"id": "opt4", "text": "Immediately request transfer", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (47, 'F', 'Telth introduces a device you have never used.', '[{"id": "opt1", "text": "Complete required training/competency validation first", "is_correct": true}, {"id": "opt2", "text": "Use without training", "is_correct": false}, {"id": "opt3", "text": "Guess", "is_correct": false}, {"id": "opt4", "text": "Refuse to learn", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (48, 'F', 'Scheduled work finishes early.', '[{"id": "opt1", "text": "Review follow-ups, documentation and partner development", "is_correct": true}, {"id": "opt2", "text": "Pretend busy", "is_correct": false}, {"id": "opt3", "text": "Leave without process", "is_correct": false}, {"id": "opt4", "text": "Ignore pending work", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (49, 'F', 'A team member challenges your idea with good evidence.', '[{"id": "opt1", "text": "Evaluate evidence and change course if appropriate", "is_correct": true}, {"id": "opt2", "text": "Reject it", "is_correct": false}, {"id": "opt3", "text": "Punish them", "is_correct": false}, {"id": "opt4", "text": "Stop speaking", "is_correct": false}]'::jsonb, true);
insert into mcq_questions (source_no, section, question_text, options, is_active) values (50, 'F', 'Best predictor of long-term growth:', '[{"id": "opt1", "text": "Continuous learning, measurable goals, accountability and ethical execution", "is_correct": true}, {"id": "opt2", "text": "Blaming circumstances", "is_correct": false}, {"id": "opt3", "text": "Avoiding feedback", "is_correct": false}, {"id": "opt4", "text": "Waiting for promotion", "is_correct": false}]'::jsonb, true);

insert into written_questions (display_order, prompt, is_active) values (1, 'Describe a professional mistake you made, how you corrected it, and what changed afterward.', true);
insert into written_questions (display_order, prompt, is_active) values (2, 'How would you build 250 active Care Plan members in a new territory without misleading sales practices?', true);
insert into written_questions (display_order, prompt, is_active) values (3, 'How would you coordinate an elderly member with multiple appointments, medicines and home-monitoring requirements?', true);
insert into written_questions (display_order, prompt, is_active) values (4, 'Describe a difficult customer/patient interaction and how you handled it.', true);
insert into written_questions (display_order, prompt, is_active) values (5, 'What are your 12-month professional goals and three measurable actions?', true);
insert into written_questions (display_order, prompt, is_active) values (6, 'Why do you want to become a Telth Care Manager and what do you believe the role is responsible for?', true);

-- Pass mark: candidates need this % or higher on the 50 objective questions to be marked 'pass'
insert into settings (key, value) values ('pass_percentage', '60')
  on conflict (key) do update set value = excluded.value;
